# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from attendance.grpc_generated import face_service_pb2 as face__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in face_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FaceServiceStub:
    """Face recognition service — replaces HTTP polling for embedded clients (Flutter).
    Browser clients continue to use the HTTP endpoints (gRPC-web requires Envoy proxy).

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScanGate = channel.unary_unary(
                '/shamel.FaceService/ScanGate',
                request_serializer=face__service__pb2.FrameRequest.SerializeToString,
                response_deserializer=face__service__pb2.GateScanResponse.FromString,
                _registered_method=True)
        self.ScanLecture = channel.unary_unary(
                '/shamel.FaceService/ScanLecture',
                request_serializer=face__service__pb2.LectureFrameRequest.SerializeToString,
                response_deserializer=face__service__pb2.LectureScanResponse.FromString,
                _registered_method=True)
        self.LoginFace = channel.unary_unary(
                '/shamel.FaceService/LoginFace',
                request_serializer=face__service__pb2.FrameRequest.SerializeToString,
                response_deserializer=face__service__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.EnrollFace = channel.unary_unary(
                '/shamel.FaceService/EnrollFace',
                request_serializer=face__service__pb2.EnrollRequest.SerializeToString,
                response_deserializer=face__service__pb2.EnrollResponse.FromString,
                _registered_method=True)
        self.LiveGateFeed = channel.unary_stream(
                '/shamel.FaceService/LiveGateFeed',
                request_serializer=face__service__pb2.LiveFeedRequest.SerializeToString,
                response_deserializer=face__service__pb2.GateEvent.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/shamel.FaceService/HealthCheck',
                request_serializer=face__service__pb2.HealthRequest.SerializeToString,
                response_deserializer=face__service__pb2.HealthResponse.FromString,
                _registered_method=True)


class FaceServiceServicer:
    """Face recognition service — replaces HTTP polling for embedded clients (Flutter).
    Browser clients continue to use the HTTP endpoints (gRPC-web requires Envoy proxy).

    """

    def ScanGate(self, request, context):
        """Gate entry: match face, log GateLog, return person info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScanLecture(self, request, context):
        """Lecture attendance: match face against enrolled course students
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginFace(self, request, context):
        """Face login: match face, return auth token
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnrollFace(self, request, context):
        """Face enrollment: store embedding for a person
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LiveGateFeed(self, request, context):
        """Live gate event stream (replaces WebSocket for native clients)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Check engine status and DB embedding health
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScanGate': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanGate,
                    request_deserializer=face__service__pb2.FrameRequest.FromString,
                    response_serializer=face__service__pb2.GateScanResponse.SerializeToString,
            ),
            'ScanLecture': grpc.unary_unary_rpc_method_handler(
                    servicer.ScanLecture,
                    request_deserializer=face__service__pb2.LectureFrameRequest.FromString,
                    response_serializer=face__service__pb2.LectureScanResponse.SerializeToString,
            ),
            'LoginFace': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginFace,
                    request_deserializer=face__service__pb2.FrameRequest.FromString,
                    response_serializer=face__service__pb2.LoginResponse.SerializeToString,
            ),
            'EnrollFace': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrollFace,
                    request_deserializer=face__service__pb2.EnrollRequest.FromString,
                    response_serializer=face__service__pb2.EnrollResponse.SerializeToString,
            ),
            'LiveGateFeed': grpc.unary_stream_rpc_method_handler(
                    servicer.LiveGateFeed,
                    request_deserializer=face__service__pb2.LiveFeedRequest.FromString,
                    response_serializer=face__service__pb2.GateEvent.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=face__service__pb2.HealthRequest.FromString,
                    response_serializer=face__service__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shamel.FaceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shamel.FaceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FaceService:
    """Face recognition service — replaces HTTP polling for embedded clients (Flutter).
    Browser clients continue to use the HTTP endpoints (gRPC-web requires Envoy proxy).

    """

    @staticmethod
    def ScanGate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shamel.FaceService/ScanGate',
            face__service__pb2.FrameRequest.SerializeToString,
            face__service__pb2.GateScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScanLecture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shamel.FaceService/ScanLecture',
            face__service__pb2.LectureFrameRequest.SerializeToString,
            face__service__pb2.LectureScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoginFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shamel.FaceService/LoginFace',
            face__service__pb2.FrameRequest.SerializeToString,
            face__service__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnrollFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shamel.FaceService/EnrollFace',
            face__service__pb2.EnrollRequest.SerializeToString,
            face__service__pb2.EnrollResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LiveGateFeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/shamel.FaceService/LiveGateFeed',
            face__service__pb2.LiveFeedRequest.SerializeToString,
            face__service__pb2.GateEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shamel.FaceService/HealthCheck',
            face__service__pb2.HealthRequest.SerializeToString,
            face__service__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
