# Generated by Django 6.0.2 on 2026-04-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_classroom_college_course_department_role_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
