# Generated by Django 6.0.2 on 2026-04-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_classroom_is_occupied'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_trained',
            field=models.BooleanField(default=False),
        ),
    ]
