# Generated by Django 6.0.1 on 2026-05-19 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_auditlog'),
        ('attendance', '0009_pgvector_embeddings'),
    ]

    operations = [
    ]
