# Generated by Django 6.0.1 on 2026-05-19 18:31
# Modified: VectorField replaced with TextField for SQLite compatibility.
# On PostgreSQL the VectorField is set via a separate pgvector migration.

from django.db import migrations, models
import django.db.models.fields


class SafeVectorField(models.TextField):
    """TextField stand-in for SQLite; PostgreSQL uses the real VectorField."""
    pass


def _is_postgres(schema_editor):
    return schema_editor.connection.vendor == 'postgresql'


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_merge_0009_auditlog_0009_pgvector_embeddings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name, e.g. Gate Camera', max_length=100)),
                ('source', models.CharField(default='0', help_text="'0' for built-in, '1' for USB, or RTSP URL", max_length=500)),
                ('location', models.CharField(blank=True, help_text='Physical location, e.g. Main Gate', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Camera Source',
                'verbose_name_plural': 'Camera Sources',
                'ordering': ['id'],
            },
        ),
        # VectorField alteration — only applied on PostgreSQL
        migrations.RunPython(
            lambda apps, se: None,   # no-op forward on SQLite
            lambda apps, se: None,   # no-op reverse
        ),
    ]
