# Generated by Django 6.0.1 on 2026-05-19 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_add_year_level_course'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='request_type',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.college'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('urgent', 'عاجل')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='ticket_type',
            field=models.CharField(choices=[('technical', 'مشكلة تقنية'), ('academic', 'مشكلة أكاديمية'), ('attendance', 'مشكلة حضور'), ('grade', 'مشكلة درجات'), ('access', 'مشكلة دخول'), ('other', 'أخرى')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوح'), ('investigating', 'قيد التحقيق'), ('resolved', 'تم الحل'), ('closed', 'مغلق')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='TicketResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_internal', models.BooleanField(default=False)),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='attendance.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
