# Generated by Django 5.2.14 on 2026-05-23 00:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aiattendancelog',
            index=models.Index(fields=['student', 'status'], name='attendlog_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'course'], name='enrollment_student_course_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student'], name='enrollment_student_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student'], name='grade_student_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'course'], name='grade_student_course_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['entered_by'], name='grade_entered_by_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturesession',
            index=models.Index(fields=['schedule', 'is_active'], name='lecture_schedule_active_idx'),
        ),
        migrations.AddIndex(
            model_name='lecturesession',
            index=models.Index(fields=['is_active'], name='lecture_active_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notif_user_read_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notif_user_date_idx'),
        ),
    ]
