# Generated by Django 6.0.1 on 2026-05-25 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_systemconfig'),
        ('attendance', '0020_performance_indexes_v2'),
    ]

    operations = [
    ]
