# Generated by Django 6.0.1 on 2026-06-25 11:23

import django.db.models.deletion
import django.utils.timezone
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0031_face_embedding_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('task_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('result', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'attendance_asynctask',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target_model', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'attendance_auditlog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('university_email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'attendance_coordinator',
            },
        ),
        migrations.CreateModel(
            name='CourseEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=10)),
                ('rating', models.IntegerField(default=3)),
                ('comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attendance_courseevaluation',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(default='Final', max_length=50)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('semester', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'attendance_exam',
            },
        ),
        migrations.CreateModel(
            name='ExamSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'attendance_examseat',
            },
        ),
        migrations.CreateModel(
            name='FinancialStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Partial', 'Partial')], default='Unpaid', max_length=10)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'attendance_financialstatus',
            },
        ),
        migrations.CreateModel(
            name='GateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('Allowed', 'Allowed'), ('Denied', 'Denied'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='gate_snapshots/')),
            ],
            options={
                'db_table': 'attendance_gatelog',
            },
        ),
        migrations.CreateModel(
            name='MedicalExcuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='excuses/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('review_note', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'attendance_medicalexcuse',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_reply', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'attendance_supportticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'attendance_system_config',
            },
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='attendancelog',
            name='student',
        ),
        migrations.DeleteModel(
            name='GateEntryLog',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='studentbiometric',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teacherattendancelog',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='camerasource',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='aiattendancelog',
            name='unique_student_per_session',
        ),
        migrations.RemoveIndex(
            model_name='aiattendancelog',
            name='attendance_session_idx',
        ),
        migrations.RemoveIndex(
            model_name='aiattendancelog',
            name='attendance_session_status_idx',
        ),
        migrations.RenameIndex(
            model_name='aiattendancelog',
            new_name='attendance__timesta_4592b9_idx',
            old_name='ail_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='aiattendancelog',
            new_name='attendance__status_12ee89_idx',
            old_name='ail_status_idx',
        ),
        migrations.RenameIndex(
            model_name='aiattendancelog',
            new_name='attendance__student_db58f9_idx',
            old_name='ail_student_status_idx',
        ),
        migrations.RenameIndex(
            model_name='aiattendancelog',
            new_name='attendance__schedul_7d2479_idx',
            old_name='ail_schedule_status_idx',
        ),
        migrations.RenameIndex(
            model_name='aiattendancelog',
            new_name='attendance__student_d09522_idx',
            old_name='ail_student_ts_idx',
        ),
        migrations.RemoveField(
            model_name='camerasource',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='is_occupied',
        ),
        migrations.RemoveField(
            model_name='department',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notif_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='encrypted_data',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_trained',
        ),
        migrations.AddField(
            model_name='aiattendancelog',
            name='method',
            field=models.CharField(default='face_recognition', max_length=50),
        ),
        migrations.AddField(
            model_name='camerasource',
            name='is_gate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classroom',
            name='capacity',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='classroom',
            name='classroom_type',
            field=models.CharField(choices=[('Lecture', 'Lecture'), ('Lab', 'Lab'), ('Hall', 'Hall')], default='Lecture', max_length=50),
        ),
        migrations.AddField(
            model_name='college',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.college'),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='total_hours',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='course',
            name='year_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.college'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturesession',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturesession',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturesession',
            name='opened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='level',
            field=models.CharField(choices=[('info', 'info'), ('warning', 'warning'), ('danger', 'danger'), ('success', 'success')], default='info', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='batch',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='semester',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='auth_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_faces/'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='university_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='teacher',
            name='auth_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacher',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.college'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.department'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_faces/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='university_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='aiattendancelog',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aiattendancelog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aiattendancelog',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.schedule'),
        ),
        migrations.AlterField(
            model_name='aiattendancelog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='camerasource',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='camerasource',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='camerasource',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='camerasource',
            name='source',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='college',
            name='college_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.classroom'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='semester',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='lecturesession',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lecturesession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lecturesession',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.schedule'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.classroom'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day_of_week',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='studentfaceembedding',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=512),
        ),
        migrations.AlterField(
            model_name='studentfaceembedding',
            name='extra_embeddings',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='studentfaceembedding',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentfaceembedding',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_embedding', to='attendance.student'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='academic_degree',
            field=models.CharField(choices=[('BSc', 'BSc'), ('MSc', 'MSc'), ('PhD', 'PhD'), ('Prof', 'Professor')], default='PhD', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='major',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teacherfaceembedding',
            name='extra_embeddings',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='teacherfaceembedding',
            name='face_vector',
            field=pgvector.django.vector.VectorField(dimensions=512),
        ),
        migrations.AlterField(
            model_name='teacherfaceembedding',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacherfaceembedding',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='face_embedding', to='attendance.teacher'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='attendance__user_id_eb8508_idx'),
        ),
        migrations.AlterModelTable(
            name='aiattendancelog',
            table='attendance_aiattendancelog',
        ),
        migrations.AlterModelTable(
            name='camerasource',
            table='attendance_camerasource',
        ),
        migrations.AlterModelTable(
            name='classroom',
            table='attendance_classroom',
        ),
        migrations.AlterModelTable(
            name='college',
            table='attendance_college',
        ),
        migrations.AlterModelTable(
            name='course',
            table='attendance_course',
        ),
        migrations.AlterModelTable(
            name='department',
            table='attendance_department',
        ),
        migrations.AlterModelTable(
            name='enrollment',
            table='attendance_enrollment',
        ),
        migrations.AlterModelTable(
            name='lecturesession',
            table='attendance_lecturesession',
        ),
        migrations.AlterModelTable(
            name='notification',
            table='attendance_notification',
        ),
        migrations.AlterModelTable(
            name='schedule',
            table='attendance_schedule',
        ),
        migrations.AlterModelTable(
            name='student',
            table='attendance_student',
        ),
        migrations.AlterModelTable(
            name='studentfaceembedding',
            table='attendance_studentfaceembedding',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='attendance_teacher',
        ),
        migrations.AlterModelTable(
            name='teacherfaceembedding',
            table='attendance_teacherfaceembedding',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='auth_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coordinator',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.college'),
        ),
        migrations.AddField(
            model_name='courseevaluation',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.course'),
        ),
        migrations.AddField(
            model_name='courseevaluation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student'),
        ),
        migrations.AddField(
            model_name='exam',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.classroom'),
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.course'),
        ),
        migrations.AddField(
            model_name='examseat',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.exam'),
        ),
        migrations.AddField(
            model_name='examseat',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student'),
        ),
        migrations.AddField(
            model_name='financialstatus',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='attendance.student'),
        ),
        migrations.AddField(
            model_name='gatelog',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.camerasource'),
        ),
        migrations.AddField(
            model_name='gatelog',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.student'),
        ),
        migrations.AddField(
            model_name='gatelog',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.teacher'),
        ),
        migrations.AddField(
            model_name='medicalexcuse',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalexcuse',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.schedule'),
        ),
        migrations.AddField(
            model_name='medicalexcuse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AttendanceLog',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='StudentBiometric',
        ),
        migrations.DeleteModel(
            name='TeacherAttendanceLog',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
        migrations.AlterUniqueTogether(
            name='courseevaluation',
            unique_together={('student', 'course', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='examseat',
            unique_together={('exam', 'student')},
        ),
        migrations.AddIndex(
            model_name='gatelog',
            index=models.Index(fields=['timestamp'], name='attendance__timesta_7eb3de_idx'),
        ),
        migrations.AddIndex(
            model_name='gatelog',
            index=models.Index(fields=['status'], name='attendance__status_d6d18e_idx'),
        ),
        migrations.AddIndex(
            model_name='gatelog',
            index=models.Index(fields=['student', 'timestamp'], name='attendance__student_a4a75a_idx'),
        ),
    ]
